version: "3.5"

services:
  mysql-db:
    image: mysql:5.6
    container_name: lbs4biz_test_mysql
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  postgres-db:
    image: mdillon/postgis:9.4
    container_name: lbs4biz_test_postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/mysql

volumes:
  mysql_data:
  postgres_data:

#volumes:
#  mysql_data:
#    external: true
#    name: lbs4biz_mysql_data
#  postgres_data:
#    external: true
#    name: lbs4biz_postgres_data