version: "3.5"

services:
  mysql-db:
          #    image: mysql:5.6
    image: hsheth2/mysql-low-memory:5.6
    container_name: lbs4biz_test_mysql
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - mysql_data:/var/lib/mysql

  postgres-db:
    image: mdillon/postgis:9.4
    container_name: lbs4biz_test_postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/mysql

  web:
    build: .
    image: ameerabdulaziz/lbs4biz_test
    container_name: lbs4biz_test_web
    working_dir: /app/lbs4biz
    # command:  bash -c "service mosquitto start && python manage.py runserver 0.0.0.0:8000"
    command:  bash -c "service mosquitto start && gunicorn lbs4biz.wsgi:application --bind 0.0.0.0:8000"
#    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - .:/app/
      - static_volume:/tmp/lbs4biz/
#    ports:
#      - "8000:8000"
    expose:
      - 8000
    depends_on:
      - mysql-db
      - postgres-db

  nginx:
    image: nginx
    container_name: lbs4biz_test_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/tmp/lbs4biz/
    depends_on:
      - web

volumes:
  mysql_data:
  postgres_data:
<<<<<<< HEAD
  static_volume:
=======
>>>>>>> 019a5bc74e6fe47ce08cd3723e935e52b7e15e16
